name: demo
description: "A new Flutter project."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  faker: ^2.1.0
  fluttertoast: ^8.0.9
  percent_indicator: ^4.0.0
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.0
  firebase_auth: ^5.3.1
  google_maps_flutter: ^2.9.0
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  sensors_plus: ^6.1.0
  geolocator: ^13.0.1
  permission_handler: ^11.3.1
  url_launcher: ^6.3.1
  workmanager: ^0.5.2
  shared_preferences: ^2.3.2
  flutter_phone_direct_caller: ^2.1.1
  http: ^1.2.2

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/bus-stop.png
    - assets/hospital.png
    - assets/police-badge.png
    - assets/women_logo.jpg